[package]
name = "file_management"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
ratatui = "0.26.1"
crossterm = "0.27.0"
walkdir = "2.3.3"
notify = "8.2.0"
mime_guess = "2.0.4"
syntect = "5.3.0"
image = "0.25.9"
